# Generated by Django 5.1.4 on 2026-06-03 19:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=100, unique=True)),
                ('label', models.CharField(max_length=200)),
                ('is_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'dashboard_modules',
                'ordering': ['label'],
            },
        ),
        migrations.CreateModel(
            name='Widget',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('label', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('vue_component', models.CharField(help_text='Vue component name to render', max_length=100)),
                ('default_visible', models.BooleanField(default=False)),
                ('is_staff_only', models.BooleanField(default=False, help_text='Only superadmin can see this widget.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='widgets', to='dashboard.module')),
            ],
            options={
                'db_table': 'dashboard_widgets',
                'ordering': ['module', 'name'],
                'unique_together': {('module', 'name')},
            },
        ),
        migrations.CreateModel(
            name='UserDashboard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('position', models.PositiveIntegerField(default=0)),
                ('is_visible', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_widgets', to=settings.AUTH_USER_MODEL)),
                ('widget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_preferences', to='dashboard.widget')),
            ],
            options={
                'db_table': 'dashboard_user_widgets',
                'ordering': ['position'],
                'unique_together': {('user', 'widget')},
            },
        ),
    ]
