# Generated by Django 5.1.4 on 2026-06-03 19:03

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False, help_text='Auto-assigned to new users on registration.')),
                ('max_tenants', models.PositiveIntegerField(default=1, help_text='Maximum number of tenants the user can own.')),
                ('rate_limit_per_minute', models.PositiveIntegerField(default=60, help_text='Max API requests per minute (enforcement via Redis).')),
                ('requests_per_hour', models.PositiveIntegerField(default=1000, help_text='Max API requests per hour (quota).')),
                ('requests_per_day', models.PositiveIntegerField(default=10000, help_text='Max API requests per day (quota).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'plans',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('valid_from', models.DateTimeField(default=django.utils.timezone.now)),
                ('valid_to', models.DateTimeField(blank=True, help_text='NULL means currently active.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, help_text='Admin who made the change.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plan_changes_made', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='plans.plan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_subscriptions',
                'ordering': ['-valid_from'],
                'indexes': [models.Index(fields=['user', 'valid_to'], name='user_subscr_user_id_3a5398_idx')],
            },
        ),
    ]
